### ISSUE TITLE
move to drone/homebrew-drone

### ISSUE THREAD

**Issue by bradrydzewski** [Bugagazavr/homebrew-drone#1]
@Bugagazavr definitely would like to get this moved over to the drone namespace. One question for you. Is it possible to use the pre-built binary file?

```
curl http://downloads.drone.io/drone-cli/drone_darwin_amd64.tar.gz
```

I think it would be nice to use the pre-built binary file in case the user doesn't have or want go / bzr / hg / cmake / etc installed on their machine. The binary is automatically generated so it should always be up-to-date with master.

**Comment by Bugagazavr** [comment]
Thanks, now bzr, mercurial, git and go requires in `--HEAD` build

**Comment by bradrydzewski** [comment]
awesome! you should have write access to the following repository to push:
https://github.com/drone/homebrew-drone
